### ISSUE TITLE
client crash on startup with latest version

### ISSUE THREAD

**Issue by Wedge1453** [malte0811/FerriteCore#30] opened 2021-08-23 11:29 UTC
[crash-2021-08-23_10.49.05-client.txt](https://github.com/malte0811/FerriteCore/files/7031467/crash-2021-08-23_10.49.05-client.txt)

**Comment by malte0811** [comment] 2021-08-23 11:44
Duplicate of #25, you are *not* on the latest build of FerriteCore.

**Closed by malte0811** 2021-08-23 11:44 UTC
