### ISSUE TITLE
[Update 2.0.7] Creation of a world

### ISSUE THREAD

**Issue by PlatiniumOfficial** [malte0811/FerriteCore#32] opened 2021-08-23 13:05 UTC
With version 2.0.7 I don't have the problem with sodium-reforged anymore, but it's impossible to create a new world, it loads between 0/100% and doesn't do anything anymore, no error, my processor doesn't run anymore, the game still responds, I don't understand ^^.

Screen > https://i.imgur.com/X0KMv9v.png

In the logs there is nothing, the client responds but does not load anything and the logs just show the % of creation of the world :s

If you need more information don't hesitate to ask.

And when I delete it everything works fine.

**Comment by PlatiniumOfficial** [comment] 2021-08-23 13:31
I have activated JMX and at the time of the generation in a worker-main-31 here it is remained stuck I do not know if it will be able to be useful to you :s

https://hastebin.com/mazexuxape.apache

**Comment by malte0811** [comment] 2021-08-23 14:20
> And when I delete it everything works fine.

I assume "it" is FerriteCore, not sodium reforged?

I'm unable to reproduce this issue, and I don't see how any change between 2.0.5 and 2.0.7 could cause it. Can you provide a full modlist (or, if it's a Curse pack, a link to that and a version number)?

**Comment by PlatiniumOfficial** [comment] 2021-08-23 14:46
Yes I was wrong ^^.

Here is the zips with all the mods: https://www.mediafire.com/file/9r5pm9n81rzxphj/Mods.zip/file

And for the list: https://hastebin.com/vufiyiyero.less

**Comment by malte0811** [comment] 2021-08-23 15:22
With those mods and default configs I can generate a world just fine (default settings for everything). I assume it's reproducible for you, rather than a one-time thing?

**Comment by PlatiniumOfficial** [comment] 2021-08-23 16:26
I have redone an instance I have succeeded in creating a world but I could not do anything, any JVM arguments could cause problems with ferrit ?

Every time I remove ferrit I have no problem, but in version 2.0.6 I had no problem, except for setting an option to false to use sodium-reforged.

I think I'll just completely remove the mod for now and see if this problem occurs.

**Comment by PlatiniumOfficial** [comment] 2021-08-24 18:22
After doing some research and dumping the threads the problem was with another mod(s) at the time of world generation.

My apologies :s.

**Comment by malte0811** [comment] 2021-08-24 18:33
So it isn't a FerriteCore issue? In that case I'll close this.

**Closed by malte0811** 2021-08-24 18:33 UTC
Labels: can't reproduce
