### ISSUE TITLE
Incompatibility with sodium for version 3.0.2

### ISSUE THREAD

**Issue by rectified20** [malte0811/FerriteCore#26] opened 2021-08-22 17:25 UTC
i was using 3.0.1 and it was working fine, saw the 3.0.2 update and my game was stuck in a loading screen loop so i individually tested all the mods and saw sodium was causing the issue.
List of mods i use:
FerriteCore
Sodium
Indium
Hydrogen
Lithium
Enhanced block entities 
Starlight
Mod Menu
Smooth Boot
Fabric API

**Comment by malte0811** [comment] 2021-08-22 17:59
Duplicate of #25 (despite the misleading title), the problem is the same on 1.16.5 and on 1.17.1

**Closed by malte0811** 2021-08-22 17:59 UTC
