### ISSUE TITLE
Error When Loading Server

### ISSUE THREAD

**Issue by AndrewCizek** [malte0811/FerriteCore#19] opened 2021-06-11 22:38 UTC
Error when trying to open a server with the mod. Not sure what it is but here are the logs.
[debug.log](https://github.com/malte0811/FerriteCore/files/6641207/debug.log)
[latest.log](https://github.com/malte0811/FerriteCore/files/6641208/latest.log)

**Comment by malte0811** [comment] 2021-06-12 06:19
This is a known incompatibility with Statement, see https://github.com/Virtuoel/Statement/issues/5. The problem is that a fix will require changes in both Statement and FerriteCore and that @Virtuoel seems to be busy with other things.

**Comment by malte0811** [comment] 2021-06-20 13:08
I've added an option to "fix" it fully on FC's side in the latest build. Since the fix (slightly) increases memory usage and is only relevant when running with very specific mods the option is disabled by default. You can enable it by setting `populateNeighborTable` to `true` in the FerriteCore config.

**Comment by malte0811** [comment] 2021-07-02 10:42
This should be fully fixed with the latest versions of FerriteCore and Statement.

**Closed by malte0811** 2021-07-02 10:42 UTC
