### ISSUE TITLE
crash on creating new world

### ISSUE THREAD

**Issue by Flame115** [malte0811/FerriteCore#54] opened 2022-02-05 22:54 UTC
https://pastebin.com/RZZ5aHyN

**Comment by freopt** [comment] 2022-02-06 00:28
getting same crash on trying to load a world, forge

**Comment by aerialspring** [comment] 2022-02-06 00:41
Same, after updating to 4.1.0
https://paste.ee/p/vtCqW

**Comment by Camawama** [comment] 2022-02-06 03:33
Yep, new update crashing on world creation :)

**Comment by esotericist** [comment] 2022-02-06 04:14
also experienced this. but at least rolling back to 4.0 gets things going again.

**Comment by itsdinkd** [comment] 2022-02-06 06:03
https://crashy.net/iMpKE44C1ewbthYK0pPw

https://bytebin.lucko.me/DdNkFS5qca

2 players have also crashed.

**Comment by malte0811** [comment] 2022-02-06 08:02
Duplicate of #52

**Closed by malte0811** 2022-02-06 08:02 UTC
