### ISSUE TITLE
Latest ferritecore bug

### ISSUE THREAD

**Issue by red2blue** [malte0811/FerriteCore#27] opened 2021-08-22 17:46 UTC
[10:44:46] [Render thread/FATAL]: Mixin apply failed ferritecore.dedupmultipart.mixin.json:MixinMultipartModel -> net.minecraft.class_1095: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_1095::redirectCacheGet with priority 1000 cannot inject into net/minecraft/class_1095::method_4707(Lnet/minecraft/class_2680;Lnet/minecraft/class_2350;Ljava/util/Random;)Ljava/util/List; merged by me.jellysquid.mods.sodium.mixin.features.model.MixinMultipartBakedModel with priority 1000 [PREINJECT Applicator Phase -> ferritecore.dedupmultipart.mixin.json:MixinMultipartModel -> Prepare Injections ->  -> redirect$fdd000$redirectCacheGet(Ljava/util/Map;Ljava/lang/Object;)Ljava/lang/Object; -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1095::redirectCacheGet with priority 1000 cannot inject into net/minecraft/class_1095::method_4707(Lnet/minecraft/class_2680;Lnet/minecraft/class_2350;Ljava/util/Random;)Ljava/util/List; merged by me.jellysquid.mods.sodium.mixin.features.model.MixinMultipartBakedModel with priority 1000 [PREINJECT Applicator Phase -> ferritecore.dedupmultipart.mixin.json:MixinMultipartModel -> Prepare Injections ->  -> redirect$fdd000$redirectCacheGet(Ljava/util/Map;Ljava/lang/Object;)Ljava/lang/Object; -> Prepare]
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.25) ~[?:?]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at malte0811.ferritecore.impl.Deduplicator.makeMultipartModel(Deduplicator.java:42) ~[ferritecore-3.0.2-fabric.jar:?]
	at net.minecraft.client.render.model.MultipartBakedModel$Builder.redirect$fdc000$build(MultipartBakedModel:522) ~[?:?]
	at net.minecraft.client.render.model.MultipartBakedModel$Builder.build(MultipartBakedModel:116) ~[?:?]
	at net.minecraft.client.render.model.MultipartUnbakedModel.bake(MultipartUnbakedModel:96) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.bake(ModelLoader:490) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.method_4733(ModelLoader:253) ~[?:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:1010) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.upload(ModelLoader:250) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.apply(BakedModelManager:67) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.apply(BakedModelManager:19) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem:179) ~[intermediary-1.17.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:166) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window:310) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1137) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[10:44:46] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.25) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem:179) ~[intermediary-1.17.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:166) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window:310) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1137) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at malte0811.ferritecore.impl.Deduplicator.makeMultipartModel(Deduplicator.java:42) ~[ferritecore-3.0.2-fabric.jar:?]
	at net.minecraft.client.render.model.MultipartBakedModel$Builder.redirect$fdc000$build(MultipartBakedModel:522) ~[?:?]
	at net.minecraft.client.render.model.MultipartBakedModel$Builder.build(MultipartBakedModel:116) ~[?:?]
	at net.minecraft.client.render.model.MultipartUnbakedModel.bake(MultipartUnbakedModel:96) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.bake(ModelLoader:490) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.method_4733(ModelLoader:253) ~[?:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:1010) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.upload(ModelLoader:250) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.apply(BakedModelManager:67) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.apply(BakedModelManager:19) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	... 68 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [ferritecore.dedupmultipart.mixin.json:MixinMultipartModel] from phase [DEFAULT] in config [ferritecore.dedupmultipart.mixin.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at malte0811.ferritecore.impl.Deduplicator.makeMultipartModel(Deduplicator.java:42) ~[ferritecore-3.0.2-fabric.jar:?]
	at net.minecraft.client.render.model.MultipartBakedModel$Builder.redirect$fdc000$build(MultipartBakedModel:522) ~[?:?]
	at net.minecraft.client.render.model.MultipartBakedModel$Builder.build(MultipartBakedModel:116) ~[?:?]
	at net.minecraft.client.render.model.MultipartUnbakedModel.bake(MultipartUnbakedModel:96) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.bake(ModelLoader:490) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.method_4733(ModelLoader:253) ~[?:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:1010) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.upload(ModelLoader:250) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.apply(BakedModelManager:67) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.apply(BakedModelManager:19) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	... 68 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1095::redirectCacheGet with priority 1000 cannot inject into net/minecraft/class_1095::method_4707(Lnet/minecraft/class_2680;Lnet/minecraft/class_2350;Ljava/util/Random;)Ljava/util/List; merged by me.jellysquid.mods.sodium.mixin.features.model.MixinMultipartBakedModel with priority 1000 [PREINJECT Applicator Phase -> ferritecore.dedupmultipart.mixin.json:MixinMultipartModel -> Prepare Injections ->  -> redirect$fdd000$redirectCacheGet(Ljava/util/Map;Ljava/lang/Object;)Ljava/lang/Object; -> Prepare]
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.25) ~[?:?]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at malte0811.ferritecore.impl.Deduplicator.makeMultipartModel(Deduplicator.java:42) ~[ferritecore-3.0.2-fabric.jar:?]
	at net.minecraft.client.render.model.MultipartBakedModel$Builder.redirect$fdc000$build(MultipartBakedModel:522) ~[?:?]
	at net.minecraft.client.render.model.MultipartBakedModel$Builder.build(MultipartBakedModel:116) ~[?:?]
	at net.minecraft.client.render.model.MultipartUnbakedModel.bake(MultipartUnbakedModel:96) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.bake(ModelLoader:490) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.method_4733(ModelLoader:253) ~[?:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:1010) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.upload(ModelLoader:250) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.apply(BakedModelManager:67) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.apply(BakedModelManager:19) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	... 68 more

**Comment by malte0811** [comment] 2021-08-22 17:59
Duplicate of #25

**Closed by malte0811** 2021-08-22 17:59 UTC

**Comment by srnyx** [comment] 2021-08-22 18:16
@red2blue Use a paste site next time please
