### ISSUE TITLE
Forge 1.19.2 FerriteCore and Radium Reforged not playing well together anymore

### ISSUE THREAD

**Issue by morelandjo** [malte0811/FerriteCore#99] opened 2022-10-30 15:25 UTC
Forge 1.19.2
Radium 0.8.2
FerriteCore 5.0.1

Running on a fresh install with only those two mods active:

[2022-10-30-1.log](https://github.com/malte0811/FerriteCore/files/9896168/2022-10-30-1.log)

Running the game with just one or the other mod doesn't result in any crash.

**Comment by malte0811** [comment] 2022-10-31 06:38
That log only has a crash from `betterbiomeblend` in it, I assume you uploaded the wrong one? From the title I'm pretty sure this is a duplicate of https://github.com/malte0811/FerriteCore/issues/96#issuecomment-1278544397, if it's something else please put a comment on this (closed) issue and I'll reopen it.

**Closed by malte0811** 2022-10-31 06:38 UTC
