### ISSUE TITLE
Fatal Rendering crash.

### ISSUE THREAD

**Issue by SadisticalSatan** [malte0811/FerriteCore#3] opened 2021-01-28 01:07 UTC
Creates a fatal rendering crash when saving entities from **Immersive Railroading** and **Universal Mod Core**, resulting in a hard crash to desktop.

There are no crash reports generated except for the Java crash log: 
[hs_err_pid10984.log](https://github.com/malte0811/FerriteCore/files/5884097/hs_err_pid10984.log)

Removing FerriteCore fixes the problem.

**Comment by malte0811** [comment] 2021-01-28 09:11
In https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/897#issuecomment-765311326 you claimed to have reproduced the crash "in a stand alone instance of IR". Unless you uploaded the wrong crash I am a bit surprised that you're now claiming it's caused by FC. Can you explain what convinced you it's caused by FC if it happens with just IR? The original reporter in that issue does not seem to be using FC either.

**Comment by SadisticalSatan** [comment] 2021-01-28 10:08
Sorry that "stand alone IR" was actually using shaders, as I was still trying to figure out what was causing the crashing (the current build of UMC also crashes with the same error).

**Comment by malte0811** [comment] 2021-01-28 15:54
According to https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/897#issuecomment-769174972 this happens without FC as well, so I'll close this issue for now. If you have further information feel free to post it here, I'll reopen it if it's related to FC after all.

**Closed by malte0811** 2021-01-28 15:54 UTC
