### ISSUE TITLE
Stuck Loading Screen

### ISSUE THREAD

**Issue by lordlony1** [malte0811/FerriteCore#31] opened 2021-08-23 12:45 UTC
I am getting the same issue as mentioned by jaxonsie on Curse Forge with the latest update of this mod.
Mojang loading screen loads all way up main menu flashes then it goes back to loading screen and continues this in a loop.

[.Mod List.txt](https://github.com/malte0811/FerriteCore/files/7031991/default.Mod.List.txt)

Previous version still works fine.

**Comment by malte0811** [comment] 2021-08-23 14:23
I assume you've uploaded the "old" modlist, since build 3.0.1 is relatively old. 3.0.2 is what I released yesterday, I'm pretty sure that's what you're using and this is a duplicate of #25. I released a fixed build (3.0.3) earlier today, so you should update to that.

**Closed by malte0811** 2021-08-23 14:23 UTC

**Comment by lordlony1** [comment] 2021-08-23 18:03
Yes sorry I was using the 3.0.1 As was working looks like for some reason the curse forge app was not downloading the 3.0.3 updated but still the older 3.0.2.

Thanks for the fix.
