### ISSUE TITLE
[1.19.2] Watchdog FastMap

### ISSUE THREAD

**Issue by itsdinkd** [malte0811/FerriteCore#121] opened 2023-04-13 00:51 UTC
https://gist.github.com/itsdinkd/62f7379d3fe746fefb05a82ba068a4c1

**Comment by malte0811** [comment] 2023-04-15 07:38
Is this reproducible? If it is, does it happen without FerriteCore? The top stack frames are in FC, but I'm very confident that that code cannot run into an infinite loop by itself. So it's more likely to be an infinite (or very long) loop in one of the callers.

If it only happens with FC, can you give me some steps to reproduce the issue? I.e: Where can I get the modpack? Is it enough to just start a server and join it, or do I need to do anything specific? etc.

**Comment by itsdinkd** [comment] 2023-05-13 18:54
sorry for late reply, no i am unable to reproduce. the modpack is Another Quality Modpack 2.

**Comment by malte0811** [comment] 2023-05-14 13:02
I'll close this issue in that case. I strongly suspect that it's not actually caused by FC, and without a way to reproduce the issue I do not have a way to investigate it further.

**Closed as not planned by malte0811** 2023-05-14 13:02 UTC
