### ISSUE TITLE
Ferrite Core crash on worldgen

### ISSUE THREAD

**Issue by Reshy** [malte0811/FerriteCore#73] opened 2022-04-24 14:41 UTC
[06:57:43] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.ReportedException: Feature placement
	at net.minecraft.server.level.ChunkMap.m_203056_(ChunkMap.java:602) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:532) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:540) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:266) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:787) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:475) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:318) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:64) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Threading detector crash did not find other thread, missing release call?
	at malte0811.ferritecore.util.SmallThreadingDetector$CrashingState.waitUntilOrCrash(SmallThreadingDetector.java:151) ~[ferritecore-4.2.0-forge.jar%23149!/:?]
	at malte0811.ferritecore.util.SmallThreadingDetector$CrashingState.waitUntilReady(SmallThreadingDetector.java:131) ~[ferritecore-4.2.0-forge.jar%23149!/:?]
	at malte0811.ferritecore.util.SmallThreadingDetector$GlobalCrashHandler.getAndWait(SmallThreadingDetector.java:102) ~[ferritecore-4.2.0-forge.jar%23149!/:?]
	at malte0811.ferritecore.util.SmallThreadingDetector$GlobalCrashHandler.crashAcquire(SmallThreadingDetector.java:76) ~[ferritecore-4.2.0-forge.jar%23149!/:?]
	at malte0811.ferritecore.util.SmallThreadingDetector.acquire(SmallThreadingDetector.java:34) ~[ferritecore-4.2.0-forge.jar%23149!/:?]
	at net.minecraft.world.level.chunk.PalettedContainer.m_63084_(PalettedContainer.java:539) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.level.chunk.PalettedContainer.m_63091_(PalettedContainer.java:88) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.level.chunk.LevelChunkSection.m_62991_(LevelChunkSection.java:73) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.level.chunk.LevelChunkSection.m_62986_(LevelChunkSection.java:67) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.level.chunk.ProtoChunk.m_6978_(ProtoChunk.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.server.level.WorldGenRegion.m_6933_(WorldGenRegion.java:271) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.level.LevelWriter.m_7731_(LevelWriter.java:15) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.m_74488_(StructureTemplate.java:359) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.phys.shapes.DiscreteVoxelShape.m_82812_(DiscreteVoxelShape.java:233) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.phys.shapes.DiscreteVoxelShape.m_82810_(DiscreteVoxelShape.java:202) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.m_74510_(StructureTemplate.java:347) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at shetiphian.terraqueous.common.worldgen.feature.AbstractTreeFeature.place(AbstractTreeFeature.java:211) ~[terraqueous-1.18-1.9.9.jar%23247!/:1.9.9]
	at shetiphian.terraqueous.common.worldgen.feature.AbstractTreeFeature.m_142674_(AbstractTreeFeature.java:126) ~[terraqueous-1.18-1.9.9.jar%23247!/:1.9.9]
	at net.minecraft.world.level.levelgen.feature.Feature.m_204740_(Feature.java:153) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_65385_(ConfiguredFeature.java:27) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191789_(PlacedFeature.java:56) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.IntPipeline$10$1.accept(IntPipeline.java:393) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191797_(PlacedFeature.java:55) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191806_(PlacedFeature.java:44) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:475) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.md158bbe$lambda$injectLightmapSetup$1$4(ChunkStatus.java:546) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2333!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
	Suppressed: java.lang.RuntimeException: Threading detector crash did not find other thread, missing release call?
		at malte0811.ferritecore.util.SmallThreadingDetector$CrashingState.waitUntilOrCrash(SmallThreadingDetector.java:151) ~[ferritecore-4.2.0-forge.jar%23149!/:?]
		at malte0811.ferritecore.util.SmallThreadingDetector$CrashingState.waitUntilReady(SmallThreadingDetector.java:136) ~[ferritecore-4.2.0-forge.jar%23149!/:?]
		at malte0811.ferritecore.util.SmallThreadingDetector$GlobalCrashHandler.getAndWait(SmallThreadingDetector.java:102) ~[ferritecore-4.2.0-forge.jar%23149!/:?]
		at malte0811.ferritecore.util.SmallThreadingDetector$GlobalCrashHandler.crashRelease(SmallThreadingDetector.java:81) ~[ferritecore-4.2.0-forge.jar%23149!/:?]
		at malte0811.ferritecore.util.SmallThreadingDetector.release(SmallThreadingDetector.java:55) ~[ferritecore-4.2.0-forge.jar%23149!/:?]
		at net.minecraft.world.level.chunk.PalettedContainer.m_63120_(PalettedContainer.java:548) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at net.minecraft.world.level.chunk.LevelChunkSection.m_63006_(LevelChunkSection.java:63) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at net.minecraft.world.level.chunk.BulkSectionAccess.close(BulkSectionAccess.java:58) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at shetiphian.terraqueous.common.worldgen.feature.AbstractTreeFeature.m_142674_(AbstractTreeFeature.java:129) ~[terraqueous-1.18-1.9.9.jar%23247!/:1.9.9]
		at net.minecraft.world.level.levelgen.feature.Feature.m_204740_(Feature.java:153) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_65385_(ConfiguredFeature.java:27) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191789_(PlacedFeature.java:56) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
		at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
		at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
		at java.util.stream.IntPipeline$10$1.accept(IntPipeline.java:393) ~[?:?]
		at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
		at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
		at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
		at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
		at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
		at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
		at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
		at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
		at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
		at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
		at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191797_(PlacedFeature.java:55) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191806_(PlacedFeature.java:44) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:475) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at net.minecraft.world.level.chunk.ChunkStatus.md158bbe$lambda$injectLightmapSetup$1$4(ChunkStatus.java:546) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2333!/:?]
		at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
		at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
		at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
		at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

**Comment by malte0811** [comment] 2022-04-24 15:39
Duplicate of #62. I'm going to disable the problematic optimization in the next release, I have no clue how this is possible.

**Closed by malte0811** 2022-04-24 15:39 UTC
